### PR TITLE
Move vision code back into master.

### PR DESCRIPTION
**Pull request by camearle20**
We've basically gotten everything done that we wanted to in this branch.  We might branch again to add unit tests, but for now we need to focus on the robot code side.

### CODE REVIEW

**Comment by PChild** [comment]
Should the driver station code be split out into a separate repo?

Some of the comments need work- you don't need to do a comment for every line, but explaining what methods do is a good idea. And yeah, still needs unit tests.

**Comment by Masterzach32** [comment]
This looks ok, we can start comms on Tuesday?

**Comment by PChild** [comment]
Yes, those comments are better. Looks good to me for merge.

**Comment by camearle20** [comment]
Cool.  There are a couple things I want to clean up before we merge.

**Comment by Masterzach32** [comment]
Looks good.

**Pull request merged**
